language: android
android:
        components:
                - platform-tools
                - build-tools-26.0.1
                - android-26
                - extra-android-m2repository
script:
        - ./demoapp/gradlew build
before_install:
        - chmod +x gradlew
branches:
        only:
                - CITest
